name: cn_project
description: A smart ticketing system for bus stops
version: 1.0.0
environment:
  sdk: ^3.1.1
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  qr_flutter: ^4.0.0
  http: ^1.2.2
  provider: ^6.0.0 # Optional: For state management
  flutter_localizations: # Optional: For localization support
    sdk: flutter
  intl: ^0.19.0 # Optional: For internationalization and formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon_1.png
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
  - assets/images/bus_pin.png
  - assets/images/bus_stop.png
  - assets/images/bus.jpg
  - assets/images/login_card.jpg
  - assets/images/regis.jpg
  - assets/images/user_background.jpg
    # Define any assets (like images) here if needed
